### ISSUE TITLE
Evaluator fails with `UnboundLocalError: local variable 'pass_at_k' referenced before assignment.`

### ISSUE THREAD

**Issue by DevonPeroutky** [bigcode-project/bigcodebench#62]
I'm attempting to run the evaluator in a docker container, using the instructions outlined in the README. However, it keeps failing with:

```UnboundLocalError: local variable 'pass_at_k' referenced before assignment```. 

Explicitly passing in ` --pass_k` (Ex. ` --pass_k 1,2`) fails with `AttributeError: 'tuple' object has no attribute 'split'`

```
(kindo-evals-py3.11) devonperoutky@Devons-MBP-2 kindo-evals % docker run -v $(pwd):/app -v /tmp/evals:/tmp/evals bigcodebench/bigcodebench-evaluate:latest --local_execute --split instruct --subset hard --samples /tmp/evals/bigcodebench/WhiteRabbitNeo_WhiteRabbitNeo-2.5-Qwen-2.5-32B/top1.jsonl
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Generating v0.1.0_hf split: 100%|██████████| 148/148 [00:00<00:00, 777.04 examples/s]
Generating v0.1.1 split: 100%|██████████| 148/148 [00:00<00:00, 45704.39 examples/s]
Generating v0.1.2 split: 100%|██████████| 148/148 [00:00<00:00, 50607.94 examples/s]
Creating json from Arrow format: 100%|██████████| 1/1 [00:00<00:00, 48.42ba/s]

Asserting the groundtruth...
 13%|█▎        | 19/148 [00:03<00:24,  5.21it/s][nltk_data] Downloading package punkt to
[nltk_data]     /home/bigcodebenchuser/nltk_data...
 15%|█▍        | 22/148 [00:04<00:20,  6.03it/s][nltk_data]   Unzipping tokenizers/punkt.zip.
 31%|███       | 46/148 [00:07<00:17,  5.74it/s]The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
 59%|█████▉    | 87/148 [00:14<00:07,  7.71it/s][nltk_data] Downloading package stopwords to
[nltk_data]     /home/bigcodebenchuser/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
 78%|███████▊  | 116/148 [00:17<00:03,  8.56it/s][(<__test__.TestCases testMethod=test_case_3>, 'Traceback (most recent call last):\n  File "__test__.py", line 105, in test_case_3\n  File "__test__.py", line 38, in task_func\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/tsa/arima/model.py", line 395, in fit\n    res = super().fit(\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 704, in fit\n    mlefit = super(MLEModel, self).fit(start_params, method=method,\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/base/model.py", line 566, in fit\n    xopt, retvals, optim_settings = optimizer._fit(f, score, start_params,\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/base/optimizer.py", line 242, in _fit\n    xopt, retvals = func(objective, gradient, start_params, fargs, kwargs,\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/base/optimizer.py", line 659, in _fit_lbfgs\n    retvals = optimize.fmin_l_bfgs_b(func, start_params, maxiter=maxiter,\n  File "/usr/local/lib/python3.10/site-packages/scipy/optimize/lbfgsb.py", line 197, in fmin_l_bfgs_b\n    res = _minimize_lbfgsb(fun, x0, args=args, jac=jac, bounds=bounds,\n  File "/usr/local/lib/python3.10/site-packages/scipy/optimize/lbfgsb.py", line 360, in _minimize_lbfgsb\n    f, g = func_and_grad(x)\n  File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 268, in fun_and_grad\n    self._update_grad()\n  File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 238, in _update_grad\n    self._update_grad_impl()\n  File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 155, in update_grad\n    self.g = approx_derivative(fun_wrapped, self.x, f0=self.f,\n  File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_numdiff.py", line 486, in approx_derivative\n    return _dense_difference(fun_wrapped, x0, f0, h,\n  File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_numdiff.py", line 557, in _dense_difference\n    df = fun(x) - f0\n  File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_numdiff.py", line 437, in fun_wrapped\n    f = np.atleast_1d(fun(x, *args, **kwargs))\n  File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 134, in fun_wrapped\n    return fun(np.copy(x), *args)\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/base/model.py", line 534, in f\n    return -self.loglike(params, *args) / nobs\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/tsa/statespace/mlemodel.py", line 939, in loglike\n    loglike = self.ssm.loglike(complex_step=complex_step, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 1001, in loglike\n    kfilter = self._filter(**kwargs)\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/tsa/statespace/kalman_filter.py", line 921, in _filter\n    self._initialize_state(prefix=prefix, complex_step=complex_step)\n  File "/usr/local/lib/python3.10/site-packages/statsmodels/tsa/statespace/representation.py", line 1058, in _initialize_state\n    self._statespaces[prefix].initialize(self.initialization,\n  File "statsmodels/tsa/statespace/_representation.pyx", line 1373, in statsmodels.tsa.statespace._representation.dStatespace.initialize\n  File "statsmodels/tsa/statespace/_representation.pyx", line 1362, in statsmodels.tsa.statespace._representation.dStatespace.initialize\n  File "statsmodels/tsa/statespace/_initialization.pyx", line 288, in statsmodels.tsa.statespace._initialization.dInitialization.initialize\n  File "statsmodels/tsa/statespace/_initialization.pyx", line 406, in statsmodels.tsa.statespace._initialization.dInitialization.initialize_stationary_stationary_cov\n  File "statsmodels/tsa/statespace/_tools.pyx", line 1525, in statsmodels.tsa.statespace._tools._dsolve_discrete_lyapunov\nnumpy.linalg.LinAlgError: LU decomposition error.\n')]
100%|██████████| 148/148 [02:53<00:00,  1.17s/it]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/bigcodebench/evaluate.py", line 385, in <module>
    main()
  File "/usr/local/lib/python3.10/site-packages/bigcodebench/evaluate.py", line 382, in main
    Fire(evaluate)
  File "/usr/local/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/bigcodebench/evaluate.py", line 329, in evaluate
    for k, v in pass_at_k.items():
UnboundLocalError: local variable 'pass_at_k' referenced before assignment
Expected outputs computed in 173.42s
Load from previous results from /tmp/evals/bigcodebench/WhiteRabbitNeo_WhiteRabbitNeo-2.5-Qwen-2.5-32B/top1_eval_results.json
BigCodeBench-Instruct (Hard)
Groundtruth pass rate: 0.980
Please be cautious!
Failed tasks: ['BigCodeBench/418', 'BigCodeBench/417', 'BigCodeBench/917']
```

System Information:
- Platform: Apple Silicon
- OS: Sonoma 14.6

**Comment by terryyz** [comment]
Thanks for reporting the issue. I need to check if the docker image is a bit out-of-date. It seems that the default value for `pass_k` is a tuple for the docker.

Meanwhile, please try to do the evaluation w/o docker and directly use `bigcodebench.evaluate` to see how it goes :)

**Comment by DevonPeroutky** [comment]
Hey @terryyz, thanks for the super fast response! Unfortunately I seem to get the same result when running the binary directly.
```
bigcodebench.evaluate --local_execute --split instruct --subset hard --samples /tmp/evals/bigcodebench/WhiteRabbitNeo_WhiteRabbitNeo-2.5-Qwen-2.5-32B/top1.jsonl
```

Gives
```
Traceback (most recent call last):
  File "/Users/devonperoutky/Library/Caches/pypoetry/virtualenvs/kindo-evals-MZpOQW1d-py3.11/bin/bigcodebench.evaluate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/devonperoutky/Library/Caches/pypoetry/virtualenvs/kindo-evals-MZpOQW1d-py3.11/lib/python3.11/site-packages/bigcodebench/evaluate.py", line 387, in main
    Fire(evaluate)
  File "/Users/devonperoutky/Library/Caches/pypoetry/virtualenvs/kindo-evals-MZpOQW1d-py3.11/lib/python3.11/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devonperoutky/Library/Caches/pypoetry/virtualenvs/kindo-evals-MZpOQW1d-py3.11/lib/python3.11/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/devonperoutky/Library/Caches/pypoetry/virtualenvs/kindo-evals-MZpOQW1d-py3.11/lib/python3.11/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devonperoutky/Library/Caches/pypoetry/virtualenvs/kindo-evals-MZpOQW1d-py3.11/lib/python3.11/site-packages/bigcodebench/evaluate.py", line 334, in evaluate
    for k, v in pass_at_k.items():
                ^^^^^^^^^
UnboundLocalError: cannot access local variable 'pass_at_k' where it is not associated with a value
```

**Comment by terryyz** [comment]
I'll try to resolve the issue by the end of today.
Could you please evaluate w/o `--local_execute`?

**Comment by DevonPeroutky** [comment]
@terryyz Sorry for the delayed response! I totally missed this.

So I'm using `bigcodebench==0.2.1.post2`. I'm not using bigcodebench for generation, because I'm testing a custom fine-tuned model, that is hosted via my companies private LiteLLM instance. However, I'm pretty confident my generation file is at least valid because it worked when I manually uploaded it to the [HuggingFace Space](https://huggingface.co/spaces/bigcode/bigcodebench-evaluator).

For reference it looks like this:
```
...
{"task_id":"BigCodeBench/1134","completion":"import os\nimport glob\nimport hashlib\n\ndef task_func(source_dir, target_dir, prefix='#Hash: '):\n    if not os.path.exists(source_dir):\n        raise FileNotFoundError(f\"The source directory '{source_dir}' does not exist.\")\n\n    if not os.path.exists(target_dir):\n        os.makedirs(target_dir)\n\n    newly_created_files = []\n\n    # Get all files in the source directory\n    for file_path in glob.glob(os.path.join(source_dir, '*')):\n        if os.path.isfile(file_path):\n            # Read the content of the file\n            with open(file_path, 'rb') as file:\n                content = file.read()\n\n            # Compute MD5 hash of the content\n            md5_hash = hashlib.md5(content).hexdigest()\n\n            # Create the new content with the hash prepended\n            new_content = (prefix + md5_hash + '\\n').encode('utf-8') + content\n\n            # Define the path for the new file in the target directory\n            new_file_path = os.path.join(target_dir, os.path.basename(file_path))\n\n            # Write the new content to the new file\n            with open(new_file_path, 'wb') as new_file:\n                new_file.write(new_content)\n\n            # Add the new file path to the list\n            newly_created_files.append(new_file_path)\n\n    return newly_created_files"}
{"task_id":"BigCodeBench/1124","completion":"import re\nfrom urllib.parse import urlparse\nfrom bs4 import BeautifulSoup\nimport requests\n\ndef task_func(myString):\n    url_pattern = re.compile(r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\\\(\\\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+')\n    urls = url_pattern.findall(myString)\n\n    if not urls:\n        return \"No valid URL found in the provided string.\"\n\n    url = urls[0]\n\n    try:\n        response = requests.get(url)\n        response.raise_for_status()\n\n        soup = BeautifulSoup(response.content, 'html.parser')\n        title = soup.find('title')\n\n        if title:\n            return title.get_text()\n        else:\n            return \"No title tag found in the webpage.\"\n\n    except requests.exceptions.RequestException as e:\n        return f\"Unable to fetch the content of the URL: {url}\""}
...
```

**Comment by terryyz** [comment]
@DevonPeroutky  The `bigcodebench.evaluate` w/o `--local_execute` will also use the same HF Space. Does the remote execution give you the expected results?

The `"completion"` inside the provided reference should actually be `"solution"` so that it can be read correctly.

Plus, I've uploaded a new docker image.

**Comment by terryyz** [comment]
Try again with `pip install -U bigcodebench` and it should be fixed now.

**Comment by zhangchen-xu** [comment]
Hi! I encountered new issues when using both docker and local execution. 

When using docker with the latest v0.2.1.post3, the error is `exec /usr/local/bin/dockerd-entrypoint.sh: no such file or directory`(and platform is changed to `linux/arm64/v8`).

For using local evaluation, the error is from Matplotlib: `matplotlib/_c_internal_utils.cpython-310-x86_64-linux-gnu.so: failed to map segment from shared object`. I tried the latest bigcodebench using different machines and all of them have this error.

Remote execution looks great from my side! 

Could you please take a look at it? Thank you for your help!

**Comment by terryyz** [comment]
@zhangchen-xu Thanks for reporting the issue! Working on it now :)

**Comment by terryyz** [comment]
The docker image should be fixed. I've confirmed that it can be run on another Linux server at least.
@zhangchen-xu @DevonPeroutky

**Comment by ishaan-jaff** [comment]
> fine-tuned model, that is hosted on my company's private LiteLLM instance.

Hi @DevonPeroutky, I'm the LiteLLM maintainer. Can we get on a call to get your feedback on LiteLLM ? 

We're planning roadmap and I'd love to get your feedback on the product 

Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by terryyz** [comment]
Closed.
